import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from './providers'
import ThemeSwitch from "@/app/components/ThemeSwitch";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <div className='bg-gray-50 dark:bg-gray-900 flex justify-end'>
            <ThemeSwitch />
          </div>
          {children}
        </Providers>
      </body>
    </html>
  );
}
